Improve error handling

diff --git a/hooks/command b/hooks/command
--- a/hooks/command
+++ b/hooks/command
@@ -564,20 +564,22 @@ function helm_deploy() {
   local chart="${BUILDKITE_PLUGIN_K8S_DEPLOY_CHART}"
   local release="${BUILDKITE_PLUGIN_K8S_DEPLOY_RELEASE}"
   local tag="${BUILDKITE_PLUGIN_K8S_DEPLOY_TAG}"
-  local namespace="${BUILDKITE_PLUGIN_K8S_NAMESPACE:-default}"
-  local random_id="$( head -c 5 /dev/urandom | base32 | tr '[:upper:]' '[:lower:]' )"
+  local namespace="${BUILDKITE_PLUGIN_K8S_DEPLOY_NAMESPACE:-default}"
+
+  echo "--- :helm: Update ${release} of ${chart} to use the image tag ${tag}"
 
   # Update the repo index - all repos
   helm repo update
 
-  # Store the overridden values in a temporary file
-  helm get values ${release} -o yaml -n ${namespace} > "/tmp/${release}-${random_id}-values.yaml"
-
   # Upgrade the image tag for the selected release
-  helm upgrade "${release}" "${chart}" -f "/tmp/${release}-${random_id}-values.yaml" --set image.tag="${DOCKER_TAG}" -n ${namespace}
+  helm upgrade --atomic --reuse-values --set image.tag="${tag}" -n "${namespace}" "${release}" "${chart}"
 
-  # Cleanup
-  rm "/tmp/${release}-${random_id}-values.yaml"
+  if [ "$?" -ne "0" ]; then
+    echo "--- :bk-status-failed: Failed to update ${release} of ${chart}"
+    exit 1
+  fi
+
+  exit 0
 }
 
 case "$BUILDKITE_PLUGIN_K8S_DEPLOY_ACTION" in
