Initial image promotion

diff --git a/hooks/command b/hooks/command
--- a/hooks/command
+++ b/hooks/command
@@ -18,15 +18,15 @@ function updateImage () {
 
     local namespace="$BUILDKITE_PLUGIN_K8S_DEPLOY_NAMESPACE"
     local deploymentName="$BUILDKITE_PLUGIN_K8S_DEPLOY_DEPLOYMENTNAME"
-    local timeout="${BUILDKITE_PLUGIN_K8S_DEPLOY_TIMEOUT:-60s}"
+    local timeout="${BUILDKITE_PLUGIN_K8S_DEPLOY_TIMEOUT:-300}s"
     local annotation="Buildkite deploy $(date +'%d-%m-%Y %H:%M')."
 
     if [[ ! -z "${BUILDKITE_UNBLOCKER}" ]]; then
         annotation="${annotation} unblocker='${BUILDKITE_UNBLOCKER}'"
     fi
 
-    local gitcommitstring=$(git log --oneline -n 1) || ""
-    if [[ ! -z "${gitcommitstring}" ]]; then
+    local gitcommitstring=$(git log --oneline -n 1) || "$BUILDKITE_COMMIT $BUILDKITE_MESSAGE"
+    if [[ ! -z "${BUILDKITE_MESSAGE}" ]]; then
         annotation="${annotation} commit='${gitcommitstring}'"
     fi
 
@@ -52,9 +52,111 @@ function updateImage () {
         fi
         exit 1
     fi
-
 }
 
-if [[ "$BUILDKITE_PLUGIN_K8S_DEPLOY_ACTION" == "updateImage" ]] ; then
-    updateImage
-fi
+function promoteImage () {
+    aws ecr get-login-password --region $BUILDKITE_PLUGIN_K8S_DEPLOY_SOURCEIMAGE_REGION | docker login --username AWS --password-stdin $BUILDKITE_PLUGIN_K8S_DEPLOY_SOURCEIMAGE_REPOSITORYURL
+    if [ $? -ne 0 ]; then
+        echo "--- :bk-status-failed: Promotion failed. Authentication failed with source repository"
+        exit 1
+    fi
+
+
+    docker pull $BUILDKITE_PLUGIN_K8S_DEPLOY_SOURCEIMAGE_REPOSITORYURL/$BUILDKITE_PLUGIN_K8S_DEPLOY_SOURCEIMAGE_IMAGE
+    if [ $? -ne 0 ]; then
+        echo "--- :bk-status-failed: Promotion failed. Failed to pull source image"
+        exit 1
+    fi
+
+    local i=0
+    local destinationimage="BUILDKITE_PLUGIN_K8S_DEPLOY_DESTINATIONIMAGES_${i}_IMAGE"
+    local destinationrepositoryurl="BUILDKITE_PLUGIN_K8S_DEPLOY_DESTINATIONIMAGES_${i}_REPOSITORYURL"
+    local destinationregion="BUILDKITE_PLUGIN_K8S_DEPLOY_DESTINATIONIMAGES_${i}_REGION"
+
+    while [[ -n "${!destinationimage:-}" ]] ; do
+        # Authenticate with the destination region
+        aws ecr get-login-password --region ${!destinationregion} | docker login --username AWS --password-stdin ${!destinationrepositoryurl}
+        if [ $? -ne 0 ]; then
+            echo "--- :bk-status-failed: Promotion failed. Authentication failed with destination repository ${!destinationrepositoryurl}"
+            exit 1
+        fi
+        
+        # Tag and push the image
+        docker tag $BUILDKITE_PLUGIN_K8S_DEPLOY_SOURCEIMAGE_REPOSITORYURL/$BUILDKITE_PLUGIN_K8S_DEPLOY_SOURCEIMAGE_IMAGE ${!destinationrepositoryurl}/${!destinationimage}
+        docker push ${!destinationrepositoryurl}/${!destinationimage}
+        if [ $? -ne 0 ]; then
+            echo "--- :bk-status-failed: Promotion failed. Push failed to destination repository ${!destinationrepositoryurl}"
+            exit 1
+        fi
+
+        # Cleanup the tag locally
+        docker rmi ${!destinationrepositoryurl}/${!destinationimage}
+
+        i=$((i+1))
+        destinationimage="BUILDKITE_PLUGIN_K8S_DEPLOY_DESTINATIONIMAGES_${i}_IMAGE"
+        destinationrepositoryurl="BUILDKITE_PLUGIN_K8S_DEPLOY_DESTINATIONIMAGES_${i}_REPOSITORYURL"
+        destinationregion="BUILDKITE_PLUGIN_K8S_DEPLOY_DESTINATIONIMAGES_${i}_region"
+    done
+
+    # Clean up the pulled image
+    docker image rm $BUILDKITE_PLUGIN_K8S_DEPLOY_SOURCEIMAGE_REPOSITORYURL/$BUILDKITE_PLUGIN_K8S_DEPLOY_SOURCEIMAGE_IMAGE
+}
+
+function run_job () {
+    local templates_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )/templates/"
+    local safe_pipeline_name="$( echo "$BUILDKITE_PIPELINE_NAME" | tr '[:upper:]' '[:lower:]' | tr '_' '-' | tr ' ' '-')"
+    local random_id="$( head -c 5 /dev/urandom | base32 | tr '[:upper:]' '[:lower:]' )"
+
+    JOB_NAME="promoteImage-$safe_pipeline_name-$random_id"
+    JOB_TIMEOUT="${BUILDKITE_PLUGIN_K8S_DEPLOY_TIMEOUT:-300}"
+
+    # Create job command to promote images
+    JOB_AWS_INIT_SCRIPT="aws ecr get-login-password --region $BUILDKITE_PLUGIN_K8S_DEPLOY_SOURCEIMAGE_REGION > /tmp/creds/source ;"
+
+    JOB_SCRIPT="cat /tmp/creds/source | docker login --username AWS --password-stdin $BUILDKITE_PLUGIN_K8S_DEPLOY_SOURCEIMAGE_REPOSITORYURL ;"
+    JOB_SCRIPT="$JOB_SCRIPT docker pull $BUILDKITE_PLUGIN_K8S_DEPLOY_SOURCEIMAGE_REPOSITORYURL/$BUILDKITE_PLUGIN_K8S_DEPLOY_SOURCEIMAGE_IMAGE ;"
+
+    local i=0
+    local destinationimage="BUILDKITE_PLUGIN_K8S_DEPLOY_DESTINATIONIMAGES_${i}_IMAGE"
+    local destinationrepositoryurl="BUILDKITE_PLUGIN_K8S_DEPLOY_DESTINATIONIMAGES_${i}_REPOSITORYURL"
+    local destinationregion="BUILDKITE_PLUGIN_K8S_DEPLOY_DESTINATIONIMAGES_${i}_REGION"
+
+    while [[ -n "${!destinationimage:-}" ]] ; do
+        JOB_AWS_INIT_SCRIPT="$JOB_AWS_INIT_SCRIPT aws ecr get-login-password --region ${!destinationregion} > /tmp/creds/destination_${i} ;"
+
+        JOB_SCRIPT="$JOB_SCRIPT cat /tmp/creds/destination_${i} | docker login --username AWS --password-stdin ${!destinationrepositoryurl} ;"
+        JOB_SCRIPT="$JOB_SCRIPT docker tag $BUILDKITE_PLUGIN_K8S_DEPLOY_SOURCEIMAGE_REPOSITORYURL/$BUILDKITE_PLUGIN_K8S_DEPLOY_SOURCEIMAGE_IMAGE ${!destinationrepositoryurl}/${!destinationimage} ;"
+        JOB_SCRIPT="$JOB_SCRIPT docker push ${!destinationrepositoryurl}/${!destinationimage} ;"
+
+        i=$((i+1))
+        destinationimage="BUILDKITE_PLUGIN_K8S_DEPLOY_DESTINATIONIMAGES_${i}_IMAGE"
+        destinationrepositoryurl="BUILDKITE_PLUGIN_K8S_DEPLOY_DESTINATIONIMAGES_${i}_REPOSITORYURL"
+        destinationregion="BUILDKITE_PLUGIN_K8S_DEPLOY_DESTINATIONIMAGES_${i}_region"
+    done
+
+    echo "$JOB_NAME"
+    echo "$JOB_AWS_INIT_SCRIPT"
+    echo "$JOB_SCRIPT"
+}
+
+
+function tail_job {
+  while true ; do
+    stdbuf -o0 -e0 kubectl logs -f "job/${job_name}" 2>>/dev/null || true
+    sleep 0.2
+  done
+}
+
+
+
+case "$BUILDKITE_PLUGIN_K8S_DEPLOY_ACTION" in
+    'updateImage')
+        updateImage
+        ;;
+    'promoteImage')
+        promoteImage
+        ;;
+    *)
+        echo "Invalid action: $BUILDKITE_PLUGIN_K8S_DEPLOY_ACTION"
+        ;;
+esac
