Remove debug, fix indents

diff --git a/hooks/command b/hooks/command
--- a/hooks/command
+++ b/hooks/command
@@ -147,13 +147,6 @@ function promoteImage () {
     fi
 }
 
-BUILDKITE_PLUGIN_K8S_DEPLOY_ACTION="runJob"
-BUILDKITE_PIPELINE_NAME="staticmaps"
-
-BUILDKITE_PLUGIN_K8S_DEPLOY_JOBIMAGE="ubuntu"
-
-
-
 function run_job () {
     local templates_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )/templates"
     local safe_pipeline_name="$( echo "$BUILDKITE_PIPELINE_NAME" | tr '[:upper:]' '[:lower:]' | tr '_' '-' | tr ' ' '-')"
@@ -207,55 +200,55 @@ function run_job () {
 
 
 function tail_job_logs {
-  # Get init container names from the job file
+    # Get init container names from the job file
 
-  local init_container_names=()
-  for row in $(cat $1 | jq -r '.spec.template.spec.initContainers[] | @base64'); do
-      _jq() {
-          echo ${row} | base64 --decode | jq -r ${1}
-      }
-      init_container_names+=($(_jq '.name'))
-  done
+    local init_container_names=()
+    for row in $(cat $1 | jq -r '.spec.template.spec.initContainers[] | @base64'); do
+        _jq() {
+            echo ${row} | base64 --decode | jq -r ${1}
+        }
+        init_container_names+=($(_jq '.name'))
+    done
 
-  # Tail the logs of the init containers in order
+    # Tail the logs of the init containers in order
 
-  for container_name in "${init_container_names[@]}"; do
-    echo "--- :k8s: Container ${container_name}"
+    for container_name in "${init_container_names[@]}"; do
+        echo "--- :k8s: Container ${container_name}"
+
+        while true ; do
+            stdbuf -o0 -e0 kubectl logs -f "job/${JOB_NAME}" -c ${container_name} 2>>/dev/null
+
+            if [ $? -eq 0 ]; then
+                break
+            else
+                jobstatus=$(kubectl get job "${JOB_NAME}" -o 'jsonpath={.status.conditions[].type}')
+                if [[ "$jobstatus" == "Failed" ]]; then
+                    echo "Job failed on init container ${container_name}"
+                    return
+                fi
+            fi
+        done
+    done
+
+    # Tail the main container logs
+
+    local main_container_name=$(cat $1 | jq -r ".spec.template.spec.containers[0].name")
+
+    echo "--- :k8s: Container ${main_container_name}"
 
     while true ; do
-        stdbuf -o0 -e0 kubectl logs -f "job/${JOB_NAME}" -c ${container_name} 2>>/dev/null
+        stdbuf -o0 -e0 kubectl logs -f "job/${JOB_NAME}" 2>>/dev/null
 
         if [ $? -eq 0 ]; then
             break
         else
             jobstatus=$(kubectl get job "${JOB_NAME}" -o 'jsonpath={.status.conditions[].type}')
             if [[ "$jobstatus" == "Failed" ]]; then
-                echo "Job failed on init container ${container_name}"
+                echo "Job failed on container ${main_container_name}"
                 return
             fi
         fi
     done
-  done
-
-  # Tail the main container logs
-
-  local main_container_name=$(cat $1 | jq -r ".spec.template.spec.containers[0].name")
-
-  echo "--- :k8s: Container ${main_container_name}"
-
-  while true ; do
-    stdbuf -o0 -e0 kubectl logs -f "job/${JOB_NAME}" 2>>/dev/null
-
-    if [ $? -eq 0 ]; then
-        break
-    else
-        jobstatus=$(kubectl get job "${JOB_NAME}" -o 'jsonpath={.status.conditions[].type}')
-        if [[ "$jobstatus" == "Failed" ]]; then
-            echo "Job failed on container ${main_container_name}"
-            return
-        fi
-    fi
-  done
 }
 
 case "$BUILDKITE_PLUGIN_K8S_DEPLOY_ACTION" in
