Create release if not exists

diff --git a/hooks/command b/hooks/command
--- a/hooks/command
+++ b/hooks/command
@@ -566,20 +566,44 @@ function helm_deploy() {
   local tag="${BUILDKITE_PLUGIN_K8S_DEPLOY_TAG}"
   local namespace="${BUILDKITE_PLUGIN_K8S_DEPLOY_NAMESPACE:-default}"
 
+  set -o pipefail
+
   echo "--- :helm: Update ${release} of ${chart} to use the image tag ${tag}"
 
-  echo "${BUILDKITE_PLUGIN_K8S_DEPLOY_VALUES}"
-
   # Update the repo index - all repos
-#  helm repo update
+  helm repo update
 
-  # Upgrade the image tag for the selected release
-#  helm upgrade --atomic --reuse-values --set image.tag="${tag}" -n "${namespace}" "${release}" "${chart}"
+  # Check that the requested release already present
+  status=$(helm status ${release} -n "${namespace}" | grep STATUS | cut -c 9-)
 
-  # if [ "$?" -ne "0" ]; then
-  #   echo "--- :bk-status-failed: Failed to update ${release} of ${chart}"
-  #   exit 1
-  # fi
+  if [ "$?" -ne "0" ]; then
+    # Create a new release as requested
+    local values_file="/tmp/$(head -c 5 /dev/urandom | base32 | tr '[:upper:]' '[:lower:]')-values.yml"
+
+    echo "Release ${release} not found, creating"
+
+    echo "${BUILDKITE_PLUGIN_K8S_DEPLOY_VALUES}" > "${values_file}"
+
+    helm install --atomic -f "${values_file}" --set image.tag="${tag}" -n "${namespace}" "${release}" "${chart}"
+
+    if [ "$?" -ne "0" ]; then
+      echo "--- :bk-status-failed: Failed to install ${release} of ${chart}"
+      rm -f "${values_file}"
+      exit 1
+    fi
+
+    rm -f "${values_file}"
+  else
+    echo "Found ${release}, status ${status}"
+
+    # Upgrade the image tag for the selected release
+    helm upgrade --atomic --reuse-values --set image.tag="${tag}" -n "${namespace}" "${release}" "${chart}"
+
+    if [ "$?" -ne "0" ]; then
+      echo "--- :bk-status-failed: Failed to update ${release} of ${chart}"
+      exit 1
+    fi
+  fi
 
   exit 0
 }
