Initial multi deploy

diff --git a/hooks/command b/hooks/command
--- a/hooks/command
+++ b/hooks/command
@@ -1,21 +1,143 @@
 #!/bin/bash
 
 function updateImage () {
+    # Start deploys in parallel
     local i=0
-    local image_name_envvar="BUILDKITE_PLUGIN_K8S_DEPLOY_CONTAINERS_${i}_IMAGE"
-    local container_name_envvar="BUILDKITE_PLUGIN_K8S_DEPLOY_CONTAINERS_${i}_CONTAINERNAME"
+    local deployment_name_envvar="BUILDKITE_PLUGIN_K8S_DEPLOY_DEPLOYMENTS_${i}_NAME"
+    local deploy_pids=()
+    local exit_codes=()
+    local should_rollback=0
+
+    while [[ -n "${!deployment_name_envvar:-}" ]] ; do
+        updateDeployment "$i" &
+        deploy_pids+=($!)
+
+        i=$((i+1))
+        deployment_name_envvar="BUILDKITE_PLUGIN_K8S_DEPLOY_DEPLOYMENTS_${i}_NAME"
+    done
+
+    for i in ${!deploy_pids[@]}; do
+        wait ${deploy_pids[$i]}
+
+        local deploy_exit_code=$?
+        exit_codes+=($deploy_exit_code)
+
+        if [ deploy_exit_code -ne 0 ]; then
+            should_rollback=1
+        fi
+    done
+
+    # Rollback and exit
+
+    if [ should_rollback -ne 0 ]; then
+        # Rollback any successful deployments, ignore unsuccesful ones since they should have never deployed
+
+        for i in ${!exit_codes[@]}; do
+            if [ ${exit_codes[$i]} -eq 0 ]; then
+                rollbackDeployment "${i}" &
+            fi
+        done
+
+        wait
+        exit 1
+    fi
+
+    # Wait for deployments to finish
+
+    local rollout_pids=()
+
+    for i in ${!deploy_pids[@]}; do
+        waitForDeploymentRollout "${i}" &
+        rollout_pids+=($!)
+    done
+
+    exit_codes=()
+    for i in ${!rollout_pids[@]}; do
+        wait ${rollout_pids[$i]}
+
+        local rollout_exit_code=$?
+        exit_codes+=($rollout_exit_code)
+
+        if [ rollout_exit_code -ne 0 ]; then
+            should_rollback=1
+        fi
+    done
+
+    # Rollback and exit
+
+    if [ should_rollback -ne 0 ]; then
+        # Rollback any successful deployments, ignore unsuccesful ones since they should have never deployed
+
+        for i in ${!exit_codes[@]}; do
+            if [ ${exit_codes[$i]} -eq 0 ]; then
+                rollbackDeployment "${i}" &
+            fi
+        done
+
+        wait
+        exit 1
+    fi
+
+    exit 0
+}
+
+function waitForDeploymentRollout () {
+    local deployment_index=$1
+    local namespace_envvar="BUILDKITE_PLUGIN_K8S_DEPLOY_DEPLOYMENTS_${deployment_index}_NAMESPACE"
+    local deployment_name_envvar="$BUILDKITE_PLUGIN_K8S_DEPLOY_DEPLOYMENTS_${deployment_index}_DEPLOYMENTNAME"
+
+    local namespace="${!namespace_envvar:-default}"
+    local deployment_name="${!deployment_name_envvar}"
+    local timeout="${BUILDKITE_PLUGIN_K8S_DEPLOY_TIMEOUT:-300}s"
+
+    if ! kubectl rollout status deployment/$deployment_name -n $namespace --timeout=$timeout ; then
+        echo "--- :bk-status-failed: Deploy failed '${deployment_name}'"
+        exit 1
+    fi
+
+    echo "--- :bk-status-passed: Deploy success"
+    exit 0
+}
+
+function rollbackDeployment () {
+    local deployment_index=$1
+    local namespace_envvar="BUILDKITE_PLUGIN_K8S_DEPLOY_DEPLOYMENTS_${deployment_index}_NAMESPACE"
+    local deployment_name_envvar="$BUILDKITE_PLUGIN_K8S_DEPLOY_DEPLOYMENTS_${deployment_index}_DEPLOYMENTNAME"
+
+    local namespace="${!namespace_envvar:-default}"
+    local deployment_name="${!deployment_name_envvar}"
+
+    kubectl rollout undo deployment/$deployment_name -n $namespace
+    if [ $? -ne 0 ]; then
+        echo "--- :bk-status-failed: Failed to rollback '${deployment_name}'"
+        exit 1
+    fi
+
+    exit 0
+}
+
+function updateDeployment () {
+    local deployment_index=$1
+
+    local i=0
+    local image_name_envvar="BUILDKITE_PLUGIN_K8S_DEPLOY_DEPLOYMENTS_${deployment_index}_CONTAINERS_${i}_IMAGE"
     local container_string=""
 
     # Extract each container to be updated
     while [[ -n "${!image_name_envvar:-}" ]] ; do
+        local container_name_envvar="BUILDKITE_PLUGIN_K8S_DEPLOY_DEPLOYMENTS_${deployment_index}_CONTAINERS_${i}_CONTAINERNAME"
+
         container_string=("${container_string} ${!container_name_envvar}=${!image_name_envvar}")
+
         i=$((i+1))
-        image_name_envvar="BUILDKITE_PLUGIN_K8S_DEPLOY_CONTAINERS_${i}_IMAGE"
-        container_name_envvar="BUILDKITE_PLUGIN_K8S_DEPLOY_CONTAINERS_${i}_CONTAINERNAME"
+        image_name_envvar="BUILDKITE_PLUGIN_K8S_DEPLOY_DEPLOYMENTS_${deployment_index}_CONTAINERS_${i}_IMAGE"
     done
 
-    local namespace="$BUILDKITE_PLUGIN_K8S_DEPLOY_NAMESPACE"
-    local deployment_name="$BUILDKITE_PLUGIN_K8S_DEPLOY_DEPLOYMENTNAME"
+    local namespace_envvar="BUILDKITE_PLUGIN_K8S_DEPLOY_DEPLOYMENTS_${deployment_index}_NAMESPACE"
+    local deployment_name_envvar="$BUILDKITE_PLUGIN_K8S_DEPLOY_DEPLOYMENTS_${deployment_index}_DEPLOYMENTNAME"
+
+    local namespace="${!namespace_envvar:-default}"
+    local deployment_name="${!deployment_name_envvar}"
     local timeout="${BUILDKITE_PLUGIN_K8S_DEPLOY_TIMEOUT:-300}s"
     local annotation="Buildkite deploy $(date +'%d-%m-%Y %H:%M')."
 
@@ -30,26 +152,34 @@ function updateImage () {
 
     echo "--- :kubernetes: Deploying new image to ${deployment_name}"
 
-    if [[ ! -z "${BUILDKITE_PLUGIN_K8S_DEPLOY_PATCHJSON}" ]]; then
-        echo "${BUILDKITE_PLUGIN_K8S_DEPLOY_PATCHJSON}" > "/tmp/${BUILDKITE_COMMIT}.json"
-        kubectl patch deployment/${deployment_name} --namespace="${namespace}" --type="json" -p="$(cat /tmp/${BUILDKITE_COMMIT}.json)"
+    local patch_json_envvar="BUILDKITE_PLUGIN_K8S_DEPLOY_DEPLOYMENTS_${deployment_index}_PATCHJSON"
+    if [[ ! -z "${!patch_json_envvar:-}" ]]; then
+        local temp_filename="/tmp/${deployment_index}_${BUILDKITE_COMMIT}.json"
+        echo "${!patch_json_envvar}" > $temp_filename
+
+        kubectl patch deployment/${deployment_name} --namespace="${namespace}" --type="json" -p="$(cat ${temp_filename})"
+        if [ $? -ne 0 ]; then
+            echo "--- :bk-status-failed: Deployment patch failed for '${deployment_name}'"
+            rm $temp_filename
+            exit 1
+        fi
+
+        rm $temp_filename
     fi
 
     kubectl set image deployment/$deployment_name $container_string --record -n $namespace
-
-    kubectl annotate deployment/$deployment_name kubernetes.io/change-cause="${annotation}" -n $namespace
-
-    if kubectl rollout status deployment/$deployment_name -n $namespace --timeout=$timeout ; then
-        echo "--- :bk-status-passed: Deploy success"
-    else
-        if [[ "$BUILDKITE_PLUGIN_K8S_DEPLOY_ROLLBACKONFAIL" == "true" ]]; then
-            echo "--- :bk-status-failed: Deploy failed. Rolling back to previous revision"
-            kubectl rollout undo deployment/$deployment_name -n $namespace
-        else
-            echo "--- :bk-status-failed: Deploy failed"
-        fi
+    if [ $? -ne 0 ]; then
+        echo "--- :bk-status-failed: Failed to set image for '${deployment_name}'"
         exit 1
     fi
+
+    kubectl annotate deployment/$deployment_name kubernetes.io/change-cause="${annotation}" -n $namespace
+    if [ $? -ne 0 ]; then
+        echo "--- :bk-status-failed: Failed to annotate deployment for '${deployment_name}'"
+        exit 1
+    fi
+
+    exit 0
 }
 
 function promoteImage () {
